Repository stanford-ssi/samwise-flight-software, pull requests merged in 2025-06, with the labels that each got.

#97 Initialize mock ground station code with simple command sending and beacon receiving loop.
  ground_station/README.md
  ground_station/code.py
  ground_station/lib/adafruit_rfm9x.mpy
Labels: review:need-review

#106 refactor: radio codec
  configure.sh
  ground_station/code.py
  src/drivers/logger/logger.c
  src/drivers/rfm9x/rfm9x.c
  src/drivers/rfm9x/rfm9x.h
  src/main.c
  src/packet/packet.c
  src/packet/packet.h
  src/tasks/command/command_task.c
  src/tasks/radio/radio_task.c
Labels: P1:need-to-have, type:security

#119 refactor: remove unused RFM9X transmission functions
  src/drivers/payload_uart/payload_uart.c
  src/drivers/rfm9x/rfm9x.c
  src/drivers/rfm9x/rfm9x.h
  src/tasks/diagnostics/diagnostics_task.c
  src/tasks/payload/payload_task.c
Labels: P2:nice-to-have
